### ISSUE TITLE
I noticed Sunny2456 is sitting in the "waiting for reentry" list and she was able to enter back into the contest. 

### ISSUE THREAD

**Issue by bigdred777** [bigdred777/dogegiftbot#15]
I noticed Sunny2456 is sitting in the "waiting for reentry" list.  And also she was able to enter back into the contest.   She is a legitimate winner so its correct for her to be in the "waiting for reentry".

**Comment by Doomhammer458** [comment]
i did OR when i should of done AND.

[fixed in this commit](https://github.com/Doomhammer458/dogegiftbot/commit/66fab25ef2042e3cbe83290d3ecea5ff8e61ba46)

run get_winners.py and use remove_entry("redditor") to remove entires.
