### ISSUE TITLE
Change word in winning anouncement post title.

### ISSUE THREAD

**Issue by bigdred777** [bigdred777/dogegiftbot#18]
change:

won the DogeGiftBot drawing

to:

won the DogeGiftBot giveaway

**Comment by Doomhammer458** [comment]
this one i'm going to make you do yourself :P 

you just need to make the change on line 411 and then save the file and go back to the command line and type 

git push -u origin master

**Comment by bigdred777** [comment]
thats funny because i actually tried to do it but gave up. lemme try again.  :D

**Comment by bigdred777** [comment]
hmmm i was able to change the file, then i tried this command but its not working:

git push -u origin master

**Comment by Doomhammer458** [comment]
it updated on the github so you did something right..... :D

**Comment by bigdred777** [comment]
ooh it must have merged right in.  i better be careful then! lol
