### ISSUE TITLE
Mark direct dogegiftbot wallet donations as anon and post to history amount of donation.

### ISSUE THREAD

**Issue by bigdred777** [bigdred777/dogegiftbot#2]
Mark direct dogegiftbot wallet donations as anon and post to history amount of donation.

**Comment by Doomhammer458** [comment]
done!

**Comment by bigdred777** [comment]
I would like to re-open this because i think its important for the donations that come in straight as a deposit, should be marked as anon and also put in the history. This is important so that when someone makes a donation from their wallet they will be able to see it, this builds confidence and trust I feel.
Example:

/u/doomhammer458 - 1000.0 doge
/u/meme-com-poop - 254000.0 doge
/u/betasword - 10500.0 doge
anonymous - 1000.0 doge
/u/turntablekittah - 500.0 doge
anonymous - 50.0 doge
/u/diaz1111 - 50.0 doge
/u/whatthemeat - 50.0 doge
anonymous- 10.0 doge
/u/bigdred777 - 1050.0 doge

**Comment by Doomhammer458** [comment]
so each individual anonymous donation should be listed as a line item?

so if there is a 50 doge and a 100 doge it should read:

anonymous1 50
anonymous2 100

**Comment by bigdred777** [comment]
Right, I think each one should be listed.   that way people can see their donation.

**Comment by Doomhammer458** [comment]
ok easy enough.

**Comment by bigdred777** [comment]
awesome!!!   i thought it was going to be hard so was hesitant to bring it back up.  but i really think it will make the history so much better.

**Comment by Doomhammer458** [comment]
https://github.com/bigdred777/dogegiftbot/pull/19

done
