### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by bigdred777** [bigdred777/dogegiftbot#27]
Once bot is set up on new server I think deploying an automatic backup system would be important. Have it backup the database every 30 minutes or something like that. And make sure it remotely sends copies of the backup  to at least one location, 2 being better.  I think we should be able to remote transfer to my regular server via ftp or maybe even ssh.

There is no hurry for this. I can manually backup until we can get this done.

**Comment by Doomhammer458** [comment]
i think that should be easy enough, but probably better to set up a cron job or something to do it rather than a code based solution.

**Comment by bigdred777** [comment]
ok i will this close this then.
