### ISSUE TITLE
Uniform and simplify commands

### ISSUE THREAD

**Issue by bigdred777** [bigdred777/dogegiftbot#6]
unless another way is better, I just think we should make the commands uniform.

accept [name of card] dogegiftbot    ---to---      +accept [name of card] 

pass random dogegiftbot  --to--   +pass random

send random dogegiftbot  (admins only) --to--   +send random

exit dogegiftbot (admins only)         --to--     +exit

reenter [username (without /u/)] dogegiftbot(admins only)  --to--    +reenter  [username (without /u/)]

**Comment by Doomhammer458** [comment]
https://github.com/bigdred777/dogegiftbot/pull/16

should address all of these
