### ISSUE TITLE
change text on winner post

### ISSUE THREAD

**Issue by bigdred777** [bigdred777/dogegiftbot#9]
to comply with reddit rules we need to change how the wallet is displayed on the winning post to this text:

^This ^bot ^is ^run ^on ^community ^donations. ^Donate ^by ^tipping ^through ^/u/dogetipbot ^or ^sending ^Dogecoin ^to ^+/u/dogetipbot ^@D8vVxYMKkmUKRpmG82Z6FCfwZWC4rgVT5w ^AMOUNT ^doge ^verify

**Comment by Doomhammer458** [comment]
[added with this commit](https://github.com/Doomhammer458/dogegiftbot/commit/1f4f8a0c6f491655c2d0736bf6d75a3a444381fd)
